### ISSUE TITLE
Livery Contributions

### ISSUE THREAD

**Issue by sriemmanuel787** [Sadia2000/747-400#13]
I have some liveries for this aircraft that I would like to contribute.
How can I do this?
I have them uploaded to my repo, if you want to see them.

**Comment by Sadia2000** [comment]
They look awesome! If you want we can add this to the repo. Also kindly say what license are the liveries under.

Thanks,
Avion ade.

**Comment by sriemmanuel787** [comment]
The liveries are all licensed under GNU GPL 2. As for the link, here it is:
https://github.com/sriemmanuel787/FG-Liveries/tree/main/747-400
It would be great if you could add these to the aircraft.

**Comment by Sadia2000** [comment]
Okay then, then its compatible, and if you want, I'll add them right now.

**Comment by sriemmanuel787** [comment]
Well then, it's settled!
Pleasure doing business with you :)

**Comment by Sadia2000** [comment]
Thanks to you :D

**Comment by Sadia2000** [comment]
Well I apologize for reopening this-
but I just noticed it now that most of your liveries are for the cargo variant.

However, due to a "Lightmap" issue, the windows are still visible even if its based on a cargo livery.

**Comment by sriemmanuel787** [comment]
Oh - I didn't know that.
Maybe because I don't use ALS or very high shader settings, but I never saw that when flying this.
Anyway, at least the Lufthansa livery is for the passenger variant.

**Comment by Sadia2000** [comment]
Ye. don't worry. I'll add it anyway, hopefully I will figure out how to get this thing to not work with certain liveries. Thanks anyway :D

**Comment by sriemmanuel787** [comment]
Thanks a lot!
