### ISSUE TITLE
New UV Map

### ISSUE THREAD

**Issue by sriemmanuel787** [Sadia2000/747-400#14]
Hello,

I was taking a look at the livery files for this aircraft in hopes of upscaling it for higher quality. The files have a resolution of 1024 x 4096, and if I upscale it the file would be too large to efficiently work with. Also, most of the file is just blank space that could be used for something more meaningful (e.g. bottom of the plane, more engine textures).

I know next to nothing about the rigor of 3D modelling, so forgive me in advance, but do you think you could re-export the UV map in a more conservative manner?

I understand that this would render all existing liveries useless, and I can help develop liveries for the new UV map, assuming you do it.

Thanks!!!

**Comment by SP-NTX** [comment]
There are more than 50 additional liveries in the other repos for the 744, it will be toooooo many liveries to redo, aand yes, i planned that. You can upscale it to 4096x8192, it will help

**Comment by Sadia2000** [comment]
Same as @SP-NTX

**Comment by SP-NTX** [comment]
Look at the ACA livery... It looks amazing with 4096x8192 paintkit

**Comment by sriemmanuel787** [comment]
Not sure what you mean by 4096x8192...
If the file was 4096 pixels high, it would be 16384 pixels wide, and that would be monstrous.
If you could send me a link to this ACA livery, I'd like to take a look at it. I didn't see one in this repository.
